## News API
- R client for newsAPIorg

## API key
- Go to [newsapi.org](https://newsapi.org) and register to get an API
  key.
- Save the key as an environment variable

```{r, eval=FALSE}
## my obscured key
NEWSAPI_KEY <- "4345e85e8ae1427480xxxxxxxxxxxxxx"

## save to .Renviron file
cat(
  paste0("NEWSAPI_KEY=", NEWSAPI_KEY),
  append = TRUE,
  fill = TRUE,
  file = file.path("~", ".Renviron")
)
```

## Install

- Install from Github

```{r, eval=FALSE}
## install script
if (!"devtools" %in% installed.packages()) {
  install.packages("devtools")
}
devtools::install_github("mkearney/newsAPI")

## load package
library(newsAPI)
```

## Demo
- Get all available news sources

```{r}
## get all english language news sources (made available by newsapi.org)
src <- get_sources(language = "en")

## preview data
print(src, width = 500)
```

- Pass news source names (IDs) to `get_articles` function

```{r}
## apply get_articles function to each news source
df <- lapply(src$id, get_articles)

## collapse into single data frame
df <- do.call("rbind", df)

## preview data
print(df, width = 500)
```

